engines:
 gofmt:
   enabled: true
 golint:
   enabled: true
 govet:
   enabled: true
ratings:
 paths:
 - "**.go"
exclude_paths:
- "/storage/remote/remote.pb.go"
- vendor/
- web/ui/static/vendor/
- "/web/ui/bindata.go"
