tasks:
  - init: 
      make build
    command: |
      gp sync-done build
      ./prometheus --config.file=documentation/examples/prometheus.yml
  - command: |
      cd web/ui/react-app
      gp sync-await build
      unset BROWSER
      export DANGEROUSLY_DISABLE_HOST_CHECK=true
      yarn start
    openMode: split-right
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9090
    onOpen: ignore
