run:
  modules-download-mode: vendor
  deadline: 5m

linters:
  enable:
  - golint

issues:
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck

linters-settings:
  errcheck:
    exclude: scripts/errcheck_excludes.txt
