# A example scrape configuration for running Prometheus with Scaleway.
scrape_configs:
  - job_name: 'instance'
    scaleway_sd_configs:
      - role: instance
        project: 11111111-1111-1111-1111-111111111111
        # replace with a Scaleway Secret Key https://console.scaleway.com/project/credentials
        access_key: SCWXXXXXXXXXXXXXXXXX
        secret_key: 11111111-1111-1111-1111-111111111111
    relabel_configs:
      # Only scrape targets that have a tag 'monitoring'.
      - source_labels: [__meta_scaleway_tags]
        regex: '.*,monitoring,.*'
        action: keep

  - job_name: 'baremetal'
    scaleway_sd_configs:
      - role: baremetal
        project: 11111111-1111-1111-1111-111111111111
        zone: fr-par-2
        # replace with a Scaleway Secret Key https://console.scaleway.com/project/credentials
        access_key: SCWXXXXXXXXXXXXXXXXX
        secret_key: 11111111-1111-1111-1111-111111111111
    relabel_configs:
      # Use the public IPv6 address and port 9100 to scrape the target.
      - source_labels: [__meta_scaleway_public_ipv6]
        target_label: __address__
        replacement: '[$1]:9100'
