apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: prometheus
  name: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    nodePort: 30900
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prometheus:travis
        args:
          - '-config.file=/etc/prometheus/prometheus-kubernetes.yml'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: host-volume
          mountPath: /etc/prometheus
      volumes:
      - name: host-volume
        hostPath:
          path: /home/lincai/prometheus/documentation/examples