# An example scrape configuration for running Prometheus
# with UpCloud.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Discover Node Exporter instances to scrape.
  - job_name: "node"
    upcloud_sd_configs:
      - port: 9100
        refresh_interval: 10s
    relabel_configs:
      # Only scrape targets that have a label 'monitoring'.
      - source_labels: [__meta_upcloud_server_label_monitoring]
        regex: "true"
        action: keep
