# A example scrape configuration for running Prometheus with Scaleway.

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Discover Node Exporter instances to scrape.
  - job_name: 'node'

    scaleway_sd_configs:
      - secret_key: "<replace with a Scaleway Secret Key https://console.scaleway.com/project/credentials>"
    relabel_configs:
      # Only scrape targets that have a tag 'monitoring'.
      - source_labels: [__meta_scaleway_tags]
        regex: '.*,monitoring,.*'
        action: keep

      # Use the public IPv6 address and port 9100 to scrape the target.
      - source_labels: [__meta_scaleway_public_ipv6]
        target_label: __address__
        replacement: '[$1]:9100'
