// +build go1.9

// Copyright 2018 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/Azure/azure-sdk-for-go/tools/profileBuilder

package containerregistryapi

import original "github.com/Azure/azure-sdk-for-go/services/preview/containerregistry/mgmt/2018-02-01/containerregistry/containerregistryapi"

type RegistriesClientAPI = original.RegistriesClientAPI
type OperationsClientAPI = original.OperationsClientAPI
type ReplicationsClientAPI = original.ReplicationsClientAPI
type WebhooksClientAPI = original.WebhooksClientAPI
type BuildsClientAPI = original.BuildsClientAPI
type BuildStepsClientAPI = original.BuildStepsClientAPI
type BuildTasksClientAPI = original.BuildTasksClientAPI
