---
name: Feature request
description: Suggest an idea for this project.
body:
  - type: markdown
    attributes:
      value: >-
        Please do *NOT* ask support questions in Github issues.


        If your issue is not a feature request or bug report use
        our [community support](https://prometheus.io/community/).


        There is also [commercial
        support](https://prometheus.io/support-training/) available.
  - type: textarea
    attributes:
      label: Proposal
      description: Use case. Why is this important?
      placeholder: “Nice to have” is not a good use case. :)
    validations:
      required: true
