{
 "title": "Prometheus Scrape Monitor",
 "time": { "from": "now-40m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(up, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job='$job'}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "SD  Instance/Job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum (up) by (job)" }
   ]
  },
  {
   "title": "Scrape Rt/Job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg (scrape_duration_seconds) by (job)"
    }
   ]
  },
  {
   "title": "Scrape Rt / instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (scrape_duration_seconds{job=\"$job\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Scrape Sample Total / Job",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg (scrape_samples_scraped) by (job)"
    }
   ]
  },
  {
   "title": "Scrape Relabel Sample Total / Job",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "avg (scrape_samples_post_metric_relabeling) by (job)"
    }
   ]
  },
  {
   "title": "Scrape Sample Total / instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (scrape_samples_scraped{job='$job'}) by (instance)"
    }
   ]
  },
  {
   "title": "Scrape Relabel Sample Total / Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (scrape_samples_post_metric_relabeling{job='$job'}) by (instance)"
    }
   ]
  },
  {
   "title": "Total Series Add / Job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg(scrape_series_added) by (job)"
    }
   ]
  },
  {
   "title": "Total Series Add / Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (scrape_series_added{job='$job'}) by (instance)"
    }
   ]
  },
  {
   "title": "SD  Instance/Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum (up) by (job)" }
   ]
  },
  {
   "title": "Scrape Rt/Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (scrape_duration_seconds) by (job)"
    }
   ]
  }
 ]
}