// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v1/services/ad_group_simulation_service.proto

package services

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	resources "google.golang.org/genproto/googleapis/ads/googleads/v1/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for
// [AdGroupSimulationService.GetAdGroupSimulation][google.ads.googleads.v1.services.AdGroupSimulationService.GetAdGroupSimulation].
type GetAdGroupSimulationRequest struct {
	// The resource name of the ad group simulation to fetch.
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdGroupSimulationRequest) Reset()         { *m = GetAdGroupSimulationRequest{} }
func (m *GetAdGroupSimulationRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdGroupSimulationRequest) ProtoMessage()    {}
func (*GetAdGroupSimulationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_100c20f45a4ce1f1, []int{0}
}

func (m *GetAdGroupSimulationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdGroupSimulationRequest.Unmarshal(m, b)
}
func (m *GetAdGroupSimulationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdGroupSimulationRequest.Marshal(b, m, deterministic)
}
func (m *GetAdGroupSimulationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdGroupSimulationRequest.Merge(m, src)
}
func (m *GetAdGroupSimulationRequest) XXX_Size() int {
	return xxx_messageInfo_GetAdGroupSimulationRequest.Size(m)
}
func (m *GetAdGroupSimulationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdGroupSimulationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdGroupSimulationRequest proto.InternalMessageInfo

func (m *GetAdGroupSimulationRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAdGroupSimulationRequest)(nil), "google.ads.googleads.v1.services.GetAdGroupSimulationRequest")
}

func init() {
	proto.RegisterFile("google/ads/googleads/v1/services/ad_group_simulation_service.proto", fileDescriptor_100c20f45a4ce1f1)
}

var fileDescriptor_100c20f45a4ce1f1 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0x26, 0xb9, 0x70, 0xe1, 0x86, 0xeb, 0x26, 0xb8, 0x28, 0x55, 0xa1, 0xd4, 0x2e, 0xa4, 0x8b,
	0x19, 0xa2, 0xc5, 0xc5, 0xd4, 0x2e, 0x92, 0x4d, 0x5c, 0x49, 0x69, 0xa1, 0x0b, 0x09, 0x84, 0xb1,
	0x33, 0x0c, 0x81, 0x26, 0x13, 0xe7, 0x24, 0xdd, 0x88, 0x1b, 0xf1, 0x0d, 0x7c, 0x03, 0x97, 0xbe,
	0x89, 0x6e, 0x7d, 0x05, 0x71, 0xe1, 0x53, 0x48, 0x3a, 0x9d, 0x80, 0xd6, 0xd8, 0xdd, 0xc7, 0x9c,
	0xef, 0xe7, 0xcc, 0x37, 0xe3, 0x04, 0x42, 0x4a, 0xb1, 0xe0, 0x98, 0x32, 0xc0, 0x1a, 0x56, 0x68,
	0xe9, 0x61, 0xe0, 0x6a, 0x99, 0xcc, 0x39, 0x60, 0xca, 0x62, 0xa1, 0x64, 0x99, 0xc7, 0x90, 0xa4,
	0xe5, 0x82, 0x16, 0x89, 0xcc, 0xe2, 0xf5, 0x10, 0xe5, 0x4a, 0x16, 0xd2, 0xed, 0x68, 0x21, 0xa2,
	0x0c, 0x50, 0xed, 0x81, 0x96, 0x1e, 0x32, 0x1e, 0xed, 0x61, 0x53, 0x8a, 0xe2, 0x20, 0x4b, 0xd5,
	0x10, 0xa3, 0xed, 0xdb, 0xfb, 0x46, 0x9c, 0x27, 0x98, 0x66, 0x99, 0x2c, 0x56, 0x43, 0xd0, 0xd3,
	0x6e, 0xe0, 0xec, 0x85, 0xbc, 0xf0, 0x59, 0x58, 0x89, 0xa7, 0xb5, 0x76, 0xc2, 0xaf, 0x4b, 0x0e,
	0x85, 0x7b, 0xe8, 0xec, 0x98, 0x8c, 0x38, 0xa3, 0x29, 0x6f, 0x59, 0x1d, 0xeb, 0xe8, 0xdf, 0xe4,
	0xbf, 0x39, 0xbc, 0xa0, 0x29, 0x3f, 0x7e, 0xb7, 0x9c, 0xd6, 0x86, 0xc3, 0x54, 0x2f, 0xef, 0x3e,
	0x5b, 0xce, 0xee, 0x4f, 0x09, 0xee, 0x08, 0x6d, 0xbb, 0x37, 0xfa, 0x65, 0xb3, 0xf6, 0xa0, 0x51,
	0x5e, 0x97, 0x82, 0x36, 0xc4, 0xdd, 0xb3, 0xbb, 0xd7, 0xb7, 0x07, 0xfb, 0xd4, 0x1d, 0x54, 0xed,
	0xdd, 0x7c, 0xb9, 0xda, 0x68, 0x5e, 0x42, 0x21, 0x53, 0xae, 0x00, 0xf7, 0x31, 0xfd, 0xae, 0x04,
	0xdc, 0xbf, 0x0d, 0xee, 0x6d, 0xa7, 0x37, 0x97, 0xe9, 0xd6, 0xc5, 0x83, 0x83, 0xa6, 0x3a, 0xc6,
	0x55, 0xe9, 0x63, 0xeb, 0xf2, 0x7c, 0x6d, 0x21, 0xe4, 0x82, 0x66, 0x02, 0x49, 0x25, 0xb0, 0xe0,
	0xd9, 0xea, 0x49, 0xcc, 0x0b, 0xe7, 0x09, 0x34, 0x7f, 0xab, 0xa1, 0x01, 0x8f, 0xf6, 0x9f, 0xd0,
	0xf7, 0x9f, 0xec, 0x4e, 0xa8, 0x0d, 0x7d, 0x06, 0x48, 0xc3, 0x0a, 0xcd, 0x3c, 0xb4, 0x0e, 0x86,
	0x17, 0x43, 0x89, 0x7c, 0x06, 0x51, 0x4d, 0x89, 0x66, 0x5e, 0x64, 0x28, 0x1f, 0x76, 0x4f, 0x9f,
	0x13, 0xe2, 0x33, 0x20, 0xa4, 0x26, 0x11, 0x32, 0xf3, 0x08, 0x31, 0xb4, 0xab, 0xbf, 0xab, 0x3d,
	0x4f, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xae, 0xdf, 0xb6, 0xd4, 0xfd, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdGroupSimulationServiceClient is the client API for AdGroupSimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdGroupSimulationServiceClient interface {
	// Returns the requested ad group simulation in full detail.
	GetAdGroupSimulation(ctx context.Context, in *GetAdGroupSimulationRequest, opts ...grpc.CallOption) (*resources.AdGroupSimulation, error)
}

type adGroupSimulationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdGroupSimulationServiceClient(cc *grpc.ClientConn) AdGroupSimulationServiceClient {
	return &adGroupSimulationServiceClient{cc}
}

func (c *adGroupSimulationServiceClient) GetAdGroupSimulation(ctx context.Context, in *GetAdGroupSimulationRequest, opts ...grpc.CallOption) (*resources.AdGroupSimulation, error) {
	out := new(resources.AdGroupSimulation)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v1.services.AdGroupSimulationService/GetAdGroupSimulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdGroupSimulationServiceServer is the server API for AdGroupSimulationService service.
type AdGroupSimulationServiceServer interface {
	// Returns the requested ad group simulation in full detail.
	GetAdGroupSimulation(context.Context, *GetAdGroupSimulationRequest) (*resources.AdGroupSimulation, error)
}

func RegisterAdGroupSimulationServiceServer(s *grpc.Server, srv AdGroupSimulationServiceServer) {
	s.RegisterService(&_AdGroupSimulationService_serviceDesc, srv)
}

func _AdGroupSimulationService_GetAdGroupSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdGroupSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdGroupSimulationServiceServer).GetAdGroupSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v1.services.AdGroupSimulationService/GetAdGroupSimulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdGroupSimulationServiceServer).GetAdGroupSimulation(ctx, req.(*GetAdGroupSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdGroupSimulationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.googleads.v1.services.AdGroupSimulationService",
	HandlerType: (*AdGroupSimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdGroupSimulation",
			Handler:    _AdGroupSimulationService_GetAdGroupSimulation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/ads/googleads/v1/services/ad_group_simulation_service.proto",
}
