// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v1/services/campaign_extension_setting_service.proto

package services

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	resources "google.golang.org/genproto/googleapis/ads/googleads/v1/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for
// [CampaignExtensionSettingService.GetCampaignExtensionSetting][google.ads.googleads.v1.services.CampaignExtensionSettingService.GetCampaignExtensionSetting].
type GetCampaignExtensionSettingRequest struct {
	// The resource name of the campaign extension setting to fetch.
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCampaignExtensionSettingRequest) Reset()         { *m = GetCampaignExtensionSettingRequest{} }
func (m *GetCampaignExtensionSettingRequest) String() string { return proto.CompactTextString(m) }
func (*GetCampaignExtensionSettingRequest) ProtoMessage()    {}
func (*GetCampaignExtensionSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc8bddcb5de716, []int{0}
}

func (m *GetCampaignExtensionSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCampaignExtensionSettingRequest.Unmarshal(m, b)
}
func (m *GetCampaignExtensionSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCampaignExtensionSettingRequest.Marshal(b, m, deterministic)
}
func (m *GetCampaignExtensionSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCampaignExtensionSettingRequest.Merge(m, src)
}
func (m *GetCampaignExtensionSettingRequest) XXX_Size() int {
	return xxx_messageInfo_GetCampaignExtensionSettingRequest.Size(m)
}
func (m *GetCampaignExtensionSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCampaignExtensionSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCampaignExtensionSettingRequest proto.InternalMessageInfo

func (m *GetCampaignExtensionSettingRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

// Request message for
// [CampaignExtensionSettingService.MutateCampaignExtensionSettings][google.ads.googleads.v1.services.CampaignExtensionSettingService.MutateCampaignExtensionSettings].
type MutateCampaignExtensionSettingsRequest struct {
	// The ID of the customer whose campaign extension settings are being
	// modified.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// The list of operations to perform on individual campaign extension
	// settings.
	Operations []*CampaignExtensionSettingOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// If true, successful operations will be carried out and invalid
	// operations will return errors. If false, all operations will be carried
	// out in one transaction if and only if they are all valid.
	// Default is false.
	PartialFailure bool `protobuf:"varint,3,opt,name=partial_failure,json=partialFailure,proto3" json:"partial_failure,omitempty"`
	// If true, the request is validated but not executed. Only errors are
	// returned, not results.
	ValidateOnly         bool     `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutateCampaignExtensionSettingsRequest) Reset() {
	*m = MutateCampaignExtensionSettingsRequest{}
}
func (m *MutateCampaignExtensionSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*MutateCampaignExtensionSettingsRequest) ProtoMessage()    {}
func (*MutateCampaignExtensionSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc8bddcb5de716, []int{1}
}

func (m *MutateCampaignExtensionSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateCampaignExtensionSettingsRequest.Unmarshal(m, b)
}
func (m *MutateCampaignExtensionSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateCampaignExtensionSettingsRequest.Marshal(b, m, deterministic)
}
func (m *MutateCampaignExtensionSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateCampaignExtensionSettingsRequest.Merge(m, src)
}
func (m *MutateCampaignExtensionSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_MutateCampaignExtensionSettingsRequest.Size(m)
}
func (m *MutateCampaignExtensionSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateCampaignExtensionSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutateCampaignExtensionSettingsRequest proto.InternalMessageInfo

func (m *MutateCampaignExtensionSettingsRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *MutateCampaignExtensionSettingsRequest) GetOperations() []*CampaignExtensionSettingOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *MutateCampaignExtensionSettingsRequest) GetPartialFailure() bool {
	if m != nil {
		return m.PartialFailure
	}
	return false
}

func (m *MutateCampaignExtensionSettingsRequest) GetValidateOnly() bool {
	if m != nil {
		return m.ValidateOnly
	}
	return false
}

// A single operation (create, update, remove) on a campaign extension setting.
type CampaignExtensionSettingOperation struct {
	// FieldMask that determines which resource fields are modified in an update.
	UpdateMask *field_mask.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// The mutate operation.
	//
	// Types that are valid to be assigned to Operation:
	//	*CampaignExtensionSettingOperation_Create
	//	*CampaignExtensionSettingOperation_Update
	//	*CampaignExtensionSettingOperation_Remove
	Operation            isCampaignExtensionSettingOperation_Operation `protobuf_oneof:"operation"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *CampaignExtensionSettingOperation) Reset()         { *m = CampaignExtensionSettingOperation{} }
func (m *CampaignExtensionSettingOperation) String() string { return proto.CompactTextString(m) }
func (*CampaignExtensionSettingOperation) ProtoMessage()    {}
func (*CampaignExtensionSettingOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc8bddcb5de716, []int{2}
}

func (m *CampaignExtensionSettingOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignExtensionSettingOperation.Unmarshal(m, b)
}
func (m *CampaignExtensionSettingOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignExtensionSettingOperation.Marshal(b, m, deterministic)
}
func (m *CampaignExtensionSettingOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignExtensionSettingOperation.Merge(m, src)
}
func (m *CampaignExtensionSettingOperation) XXX_Size() int {
	return xxx_messageInfo_CampaignExtensionSettingOperation.Size(m)
}
func (m *CampaignExtensionSettingOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignExtensionSettingOperation.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignExtensionSettingOperation proto.InternalMessageInfo

func (m *CampaignExtensionSettingOperation) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type isCampaignExtensionSettingOperation_Operation interface {
	isCampaignExtensionSettingOperation_Operation()
}

type CampaignExtensionSettingOperation_Create struct {
	Create *resources.CampaignExtensionSetting `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type CampaignExtensionSettingOperation_Update struct {
	Update *resources.CampaignExtensionSetting `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type CampaignExtensionSettingOperation_Remove struct {
	Remove string `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

func (*CampaignExtensionSettingOperation_Create) isCampaignExtensionSettingOperation_Operation() {}

func (*CampaignExtensionSettingOperation_Update) isCampaignExtensionSettingOperation_Operation() {}

func (*CampaignExtensionSettingOperation_Remove) isCampaignExtensionSettingOperation_Operation() {}

func (m *CampaignExtensionSettingOperation) GetOperation() isCampaignExtensionSettingOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *CampaignExtensionSettingOperation) GetCreate() *resources.CampaignExtensionSetting {
	if x, ok := m.GetOperation().(*CampaignExtensionSettingOperation_Create); ok {
		return x.Create
	}
	return nil
}

func (m *CampaignExtensionSettingOperation) GetUpdate() *resources.CampaignExtensionSetting {
	if x, ok := m.GetOperation().(*CampaignExtensionSettingOperation_Update); ok {
		return x.Update
	}
	return nil
}

func (m *CampaignExtensionSettingOperation) GetRemove() string {
	if x, ok := m.GetOperation().(*CampaignExtensionSettingOperation_Remove); ok {
		return x.Remove
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CampaignExtensionSettingOperation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CampaignExtensionSettingOperation_Create)(nil),
		(*CampaignExtensionSettingOperation_Update)(nil),
		(*CampaignExtensionSettingOperation_Remove)(nil),
	}
}

// Response message for a campaign extension setting mutate.
type MutateCampaignExtensionSettingsResponse struct {
	// Errors that pertain to operation failures in the partial failure mode.
	// Returned only when partial_failure = true and all errors occur inside the
	// operations. If any errors occur outside the operations (e.g. auth errors),
	// we return an RPC level error.
	PartialFailureError *status.Status `protobuf:"bytes,3,opt,name=partial_failure_error,json=partialFailureError,proto3" json:"partial_failure_error,omitempty"`
	// All results for the mutate.
	Results              []*MutateCampaignExtensionSettingResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *MutateCampaignExtensionSettingsResponse) Reset() {
	*m = MutateCampaignExtensionSettingsResponse{}
}
func (m *MutateCampaignExtensionSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*MutateCampaignExtensionSettingsResponse) ProtoMessage()    {}
func (*MutateCampaignExtensionSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc8bddcb5de716, []int{3}
}

func (m *MutateCampaignExtensionSettingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateCampaignExtensionSettingsResponse.Unmarshal(m, b)
}
func (m *MutateCampaignExtensionSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateCampaignExtensionSettingsResponse.Marshal(b, m, deterministic)
}
func (m *MutateCampaignExtensionSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateCampaignExtensionSettingsResponse.Merge(m, src)
}
func (m *MutateCampaignExtensionSettingsResponse) XXX_Size() int {
	return xxx_messageInfo_MutateCampaignExtensionSettingsResponse.Size(m)
}
func (m *MutateCampaignExtensionSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateCampaignExtensionSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutateCampaignExtensionSettingsResponse proto.InternalMessageInfo

func (m *MutateCampaignExtensionSettingsResponse) GetPartialFailureError() *status.Status {
	if m != nil {
		return m.PartialFailureError
	}
	return nil
}

func (m *MutateCampaignExtensionSettingsResponse) GetResults() []*MutateCampaignExtensionSettingResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// The result for the campaign extension setting mutate.
type MutateCampaignExtensionSettingResult struct {
	// Returned for successful operations.
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutateCampaignExtensionSettingResult) Reset()         { *m = MutateCampaignExtensionSettingResult{} }
func (m *MutateCampaignExtensionSettingResult) String() string { return proto.CompactTextString(m) }
func (*MutateCampaignExtensionSettingResult) ProtoMessage()    {}
func (*MutateCampaignExtensionSettingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc8bddcb5de716, []int{4}
}

func (m *MutateCampaignExtensionSettingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateCampaignExtensionSettingResult.Unmarshal(m, b)
}
func (m *MutateCampaignExtensionSettingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateCampaignExtensionSettingResult.Marshal(b, m, deterministic)
}
func (m *MutateCampaignExtensionSettingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateCampaignExtensionSettingResult.Merge(m, src)
}
func (m *MutateCampaignExtensionSettingResult) XXX_Size() int {
	return xxx_messageInfo_MutateCampaignExtensionSettingResult.Size(m)
}
func (m *MutateCampaignExtensionSettingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateCampaignExtensionSettingResult.DiscardUnknown(m)
}

var xxx_messageInfo_MutateCampaignExtensionSettingResult proto.InternalMessageInfo

func (m *MutateCampaignExtensionSettingResult) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetCampaignExtensionSettingRequest)(nil), "google.ads.googleads.v1.services.GetCampaignExtensionSettingRequest")
	proto.RegisterType((*MutateCampaignExtensionSettingsRequest)(nil), "google.ads.googleads.v1.services.MutateCampaignExtensionSettingsRequest")
	proto.RegisterType((*CampaignExtensionSettingOperation)(nil), "google.ads.googleads.v1.services.CampaignExtensionSettingOperation")
	proto.RegisterType((*MutateCampaignExtensionSettingsResponse)(nil), "google.ads.googleads.v1.services.MutateCampaignExtensionSettingsResponse")
	proto.RegisterType((*MutateCampaignExtensionSettingResult)(nil), "google.ads.googleads.v1.services.MutateCampaignExtensionSettingResult")
}

func init() {
	proto.RegisterFile("google/ads/googleads/v1/services/campaign_extension_setting_service.proto", fileDescriptor_eefc8bddcb5de716)
}

var fileDescriptor_eefc8bddcb5de716 = []byte{
	// 728 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x4f, 0xd4, 0x40,
	0x14, 0xc7, 0x6d, 0x21, 0x28, 0x53, 0xd4, 0x64, 0x8c, 0x71, 0xb3, 0x1a, 0x59, 0xeb, 0x46, 0xc8,
	0x1e, 0xda, 0xec, 0x7a, 0xeb, 0x06, 0x93, 0xdd, 0x95, 0x85, 0x8d, 0x41, 0x48, 0x89, 0x1c, 0xcc,
	0x26, 0x75, 0x68, 0x87, 0xa6, 0xa1, 0xed, 0xd4, 0x99, 0xe9, 0x2a, 0x21, 0x1c, 0xf4, 0x6a, 0x3c,
	0xf9, 0x0d, 0x3c, 0x7a, 0xf7, 0x4b, 0x78, 0xe5, 0x2b, 0xe8, 0xc5, 0xcf, 0xe0, 0xc1, 0xb4, 0xd3,
	0x59, 0x01, 0x53, 0x4a, 0x02, 0xb7, 0xd7, 0x37, 0xff, 0xfe, 0xde, 0x7b, 0xf3, 0x5e, 0x5f, 0xc1,
	0xc8, 0x27, 0xc4, 0x0f, 0xb1, 0x89, 0x3c, 0x66, 0x0a, 0x33, 0xb3, 0x26, 0x6d, 0x93, 0x61, 0x3a,
	0x09, 0x5c, 0xcc, 0x4c, 0x17, 0x45, 0x09, 0x0a, 0xfc, 0xd8, 0xc1, 0xef, 0x39, 0x8e, 0x59, 0x40,
	0x62, 0x87, 0x61, 0xce, 0x83, 0xd8, 0x77, 0x0a, 0x8d, 0x91, 0x50, 0xc2, 0x09, 0x6c, 0x88, 0xf7,
	0x0d, 0xe4, 0x31, 0x63, 0x8a, 0x32, 0x26, 0x6d, 0x43, 0xa2, 0xea, 0xfd, 0xb2, 0x60, 0x14, 0x33,
	0x92, 0xd2, 0xf3, 0xa3, 0x89, 0x28, 0xf5, 0x07, 0x92, 0x91, 0x04, 0x26, 0x8a, 0x63, 0xc2, 0x11,
	0x0f, 0x48, 0xcc, 0x8a, 0xd3, 0x22, 0x07, 0x33, 0x7f, 0xda, 0x4d, 0xf7, 0xcc, 0xbd, 0x00, 0x87,
	0x9e, 0x13, 0x21, 0xb6, 0x5f, 0x28, 0x1e, 0x9e, 0x55, 0xbc, 0xa3, 0x28, 0x49, 0x30, 0x95, 0x84,
	0x7b, 0xc5, 0x39, 0x4d, 0x5c, 0x93, 0x71, 0xc4, 0xd3, 0xe2, 0x40, 0x1f, 0x01, 0x7d, 0x0d, 0xf3,
	0x41, 0x91, 0xdf, 0xaa, 0x4c, 0x6f, 0x5b, 0x64, 0x67, 0xe3, 0xb7, 0x29, 0x66, 0x1c, 0x3e, 0x06,
	0x37, 0x65, 0x31, 0x4e, 0x8c, 0x22, 0x5c, 0x53, 0x1a, 0xca, 0xf2, 0xbc, 0xbd, 0x20, 0x9d, 0x2f,
	0x51, 0x84, 0xf5, 0x3f, 0x0a, 0x78, 0xb2, 0x91, 0x72, 0xc4, 0x71, 0x19, 0x8e, 0x49, 0xde, 0x22,
	0xd0, 0xdc, 0x94, 0x71, 0x12, 0x61, 0xea, 0x04, 0x5e, 0x41, 0x03, 0xd2, 0x35, 0xf2, 0xa0, 0x0b,
	0x00, 0x49, 0x30, 0x15, 0xb7, 0x50, 0x53, 0x1b, 0x33, 0xcb, 0x5a, 0x67, 0x60, 0x54, 0xb5, 0xc2,
	0x28, 0x0b, 0xbc, 0x29, 0x59, 0xf6, 0x09, 0x2c, 0x5c, 0x02, 0xb7, 0x13, 0x44, 0x79, 0x80, 0x42,
	0x67, 0x0f, 0x05, 0x61, 0x4a, 0x71, 0x6d, 0xa6, 0xa1, 0x2c, 0xdf, 0xb0, 0x6f, 0x15, 0xee, 0xa1,
	0xf0, 0x66, 0xe5, 0x4f, 0x50, 0x18, 0x78, 0x88, 0x63, 0x87, 0xc4, 0xe1, 0x41, 0x6d, 0x36, 0x97,
	0x2d, 0x48, 0xe7, 0x66, 0x1c, 0x1e, 0xe8, 0xdf, 0x55, 0xf0, 0xa8, 0x32, 0x3e, 0xec, 0x02, 0x2d,
	0x4d, 0x72, 0x50, 0xd6, 0xbd, 0x1c, 0xa4, 0x75, 0xea, 0xb2, 0x32, 0xd9, 0x3e, 0x63, 0x98, 0x35,
	0x78, 0x03, 0xb1, 0x7d, 0x1b, 0x08, 0x79, 0x66, 0xc3, 0x57, 0x60, 0xce, 0xa5, 0x18, 0x71, 0x71,
	0xff, 0x5a, 0xa7, 0x5b, 0x7a, 0x23, 0xd3, 0xd1, 0x2b, 0xbd, 0x92, 0xf5, 0x6b, 0x76, 0x01, 0xcb,
	0xb0, 0x22, 0x48, 0x4d, 0xbd, 0x12, 0xac, 0x80, 0xc1, 0x1a, 0x98, 0xa3, 0x38, 0x22, 0x13, 0x71,
	0xab, 0xf3, 0xd9, 0x89, 0x78, 0xee, 0x6b, 0x60, 0x7e, 0xda, 0x06, 0xfd, 0x58, 0x01, 0x4b, 0x95,
	0x63, 0xc3, 0x12, 0x12, 0x33, 0x0c, 0x87, 0xe0, 0xee, 0x99, 0x8e, 0x39, 0x98, 0x52, 0x42, 0xf3,
	0x08, 0x5a, 0x07, 0xca, 0xc4, 0x69, 0xe2, 0x1a, 0xdb, 0xf9, 0x98, 0xdb, 0x77, 0x4e, 0xf7, 0x72,
	0x35, 0x93, 0xc3, 0x37, 0xe0, 0x3a, 0xc5, 0x2c, 0x0d, 0xb9, 0x9c, 0xad, 0x61, 0xf5, 0x6c, 0x9d,
	0x9f, 0xa3, 0x9d, 0xe3, 0x6c, 0x89, 0xd5, 0x5f, 0x80, 0xe6, 0x45, 0x5e, 0xb8, 0xd0, 0x97, 0xd5,
	0xf9, 0x3c, 0x0b, 0x16, 0xcb, 0x38, 0xdb, 0x22, 0x3f, 0xf8, 0x4b, 0x01, 0xf7, 0xcf, 0xf9, 0x92,
	0xe1, 0xf3, 0xea, 0x0a, 0xab, 0x17, 0x41, 0xfd, 0x32, 0xa3, 0xa1, 0x0f, 0x3e, 0x1e, 0xff, 0xfc,
	0xa2, 0xae, 0xc0, 0x6e, 0xb6, 0x1c, 0x0f, 0x4f, 0x95, 0xbd, 0x22, 0xbf, 0x7d, 0x66, 0xb6, 0xa6,
	0xdb, 0xf2, 0xbf, 0x39, 0x30, 0x5b, 0x47, 0xf0, 0x83, 0x0a, 0x16, 0x2b, 0xc6, 0x05, 0xae, 0x5f,
	0xb6, 0x9b, 0x72, 0x51, 0xd5, 0x47, 0x57, 0x40, 0x12, 0xb3, 0xab, 0x8f, 0xf2, 0xea, 0x07, 0xfa,
	0xb3, 0xac, 0xfa, 0x7f, 0xe5, 0x1e, 0x9e, 0x58, 0x84, 0x2b, 0xad, 0xa3, 0xf2, 0xe2, 0xad, 0x28,
	0x0f, 0x64, 0x29, 0xad, 0xfe, 0x27, 0x15, 0x34, 0x5d, 0x12, 0x55, 0xe6, 0xd6, 0x6f, 0x56, 0x4c,
	0xcd, 0x56, 0xb6, 0x6f, 0xb6, 0x94, 0xd7, 0xeb, 0x05, 0xc9, 0x27, 0x21, 0x8a, 0x7d, 0x83, 0x50,
	0xdf, 0xf4, 0x71, 0x9c, 0x6f, 0x23, 0xf9, 0x4b, 0x4b, 0x02, 0x56, 0xfe, 0x3b, 0xed, 0x4a, 0xe3,
	0xab, 0x3a, 0xb3, 0xd6, 0xeb, 0x7d, 0x53, 0x1b, 0x6b, 0x02, 0xd8, 0xf3, 0x98, 0x21, 0xcc, 0xcc,
	0xda, 0x69, 0x1b, 0x45, 0x60, 0xf6, 0x43, 0x4a, 0xc6, 0x3d, 0x8f, 0x8d, 0xa7, 0x92, 0xf1, 0x4e,
	0x7b, 0x2c, 0x25, 0xbf, 0xd5, 0xa6, 0xf0, 0x5b, 0x56, 0xcf, 0x63, 0x96, 0x35, 0x15, 0x59, 0xd6,
	0x4e, 0xdb, 0xb2, 0xa4, 0x6c, 0x77, 0x2e, 0xcf, 0xf3, 0xe9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x75, 0x32, 0x38, 0x15, 0xf5, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CampaignExtensionSettingServiceClient is the client API for CampaignExtensionSettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CampaignExtensionSettingServiceClient interface {
	// Returns the requested campaign extension setting in full detail.
	GetCampaignExtensionSetting(ctx context.Context, in *GetCampaignExtensionSettingRequest, opts ...grpc.CallOption) (*resources.CampaignExtensionSetting, error)
	// Creates, updates, or removes campaign extension settings. Operation
	// statuses are returned.
	MutateCampaignExtensionSettings(ctx context.Context, in *MutateCampaignExtensionSettingsRequest, opts ...grpc.CallOption) (*MutateCampaignExtensionSettingsResponse, error)
}

type campaignExtensionSettingServiceClient struct {
	cc *grpc.ClientConn
}

func NewCampaignExtensionSettingServiceClient(cc *grpc.ClientConn) CampaignExtensionSettingServiceClient {
	return &campaignExtensionSettingServiceClient{cc}
}

func (c *campaignExtensionSettingServiceClient) GetCampaignExtensionSetting(ctx context.Context, in *GetCampaignExtensionSettingRequest, opts ...grpc.CallOption) (*resources.CampaignExtensionSetting, error) {
	out := new(resources.CampaignExtensionSetting)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v1.services.CampaignExtensionSettingService/GetCampaignExtensionSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignExtensionSettingServiceClient) MutateCampaignExtensionSettings(ctx context.Context, in *MutateCampaignExtensionSettingsRequest, opts ...grpc.CallOption) (*MutateCampaignExtensionSettingsResponse, error) {
	out := new(MutateCampaignExtensionSettingsResponse)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v1.services.CampaignExtensionSettingService/MutateCampaignExtensionSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignExtensionSettingServiceServer is the server API for CampaignExtensionSettingService service.
type CampaignExtensionSettingServiceServer interface {
	// Returns the requested campaign extension setting in full detail.
	GetCampaignExtensionSetting(context.Context, *GetCampaignExtensionSettingRequest) (*resources.CampaignExtensionSetting, error)
	// Creates, updates, or removes campaign extension settings. Operation
	// statuses are returned.
	MutateCampaignExtensionSettings(context.Context, *MutateCampaignExtensionSettingsRequest) (*MutateCampaignExtensionSettingsResponse, error)
}

func RegisterCampaignExtensionSettingServiceServer(s *grpc.Server, srv CampaignExtensionSettingServiceServer) {
	s.RegisterService(&_CampaignExtensionSettingService_serviceDesc, srv)
}

func _CampaignExtensionSettingService_GetCampaignExtensionSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignExtensionSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignExtensionSettingServiceServer).GetCampaignExtensionSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v1.services.CampaignExtensionSettingService/GetCampaignExtensionSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignExtensionSettingServiceServer).GetCampaignExtensionSetting(ctx, req.(*GetCampaignExtensionSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignExtensionSettingService_MutateCampaignExtensionSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateCampaignExtensionSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignExtensionSettingServiceServer).MutateCampaignExtensionSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v1.services.CampaignExtensionSettingService/MutateCampaignExtensionSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignExtensionSettingServiceServer).MutateCampaignExtensionSettings(ctx, req.(*MutateCampaignExtensionSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CampaignExtensionSettingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.googleads.v1.services.CampaignExtensionSettingService",
	HandlerType: (*CampaignExtensionSettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCampaignExtensionSetting",
			Handler:    _CampaignExtensionSettingService_GetCampaignExtensionSetting_Handler,
		},
		{
			MethodName: "MutateCampaignExtensionSettings",
			Handler:    _CampaignExtensionSettingService_MutateCampaignExtensionSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/ads/googleads/v1/services/campaign_extension_setting_service.proto",
}
