apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/prometheus?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "release-2.17"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: release-acm-217
    appstudio.openshift.io/component: prometheus-acm-217
    pipelines.appstudio.openshift.io/type: build
  name: prometheus-acm-217-on-pull-request
  namespace: crt-redhat-acm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-acm-217:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: Containerfile.operator
  - name: path-context
    value: .
  - name: hermetic
    value: true
  - name: prefetch-input
    value: '[{"path": ".", "type": "gomod"}, {"path": "promu/", "type": "gomod"}]'
  - name: build-source-image
    value: "true"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-prometheus-acm-217
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
