{
 "title": "Remote Write 1.1",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "recv_base",
    "label": "recv_base",
    "query": {
     "query": "label_values(prometheus_config_last_reload_successful,job)"
    }
   },
   {
    "name": "send_base",
    "label": "send_base",
    "query": {
     "query": "label_values(prometheus_config_last_reload_successful,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "prometheus_remote_storage_bytes_total diff",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_remote_storage_bytes_total[$__range])) by (remote_name)\n / ignoring(remote_name) group_left\n sum(increase(prometheus_remote_storage_bytes_total{remote_name=\"$recv_base\"}[$__range])) by (remote_name)\n-1\n"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(prometheus_remote_storage_bytes_total) by (remote_name)"
    }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"receiver.*|sender.*\"}) by (job)\n"
    }
   ]
  },
  {
   "title": "process_virtual_memory_bytes receiver",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{job=~\"receiver.*\"}) by (job)\n"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total diff receiver",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{job=~\"receiver-.*\"}[$__range])) by (job)\n / ignoring(job) group_left\n sum(increase(process_cpu_seconds_total{job=\"$recv_base\"}[$__range])) by (job)\n-1\n"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total receiver",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{job=~\"receiver-.*\"}) by (job)"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_head_series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=~\"receiver.*|sender.*\"}) by (job)"
    }
   ]
  },
  {
   "title": "process_virtual_memory_bytes sender",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{job=~\"sender.*\"}) by (job)\n"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total diff sender",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{job=~\"sender-.*\"}[$__range])) by (job)\n / ignoring(job) group_left\n sum(increase(process_cpu_seconds_total{job=\"$send_base\"}[$__range])) by (job)\n-1\n"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total sender",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 18 },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{job=~\"sender-.*\"}) by (job)"
    }
   ]
  }
 ]
}