---
name: Approve pending workflows

on:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  approve:
    if: >-
      github.event.issue.pull_request &&
      github.event.comment.body == '/workflow-approve' &&
      github.repository_owner == 'prometheus'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: write
    steps:
      - uses: prometheus/promci/approve_workflows@370e8c15dcec50043cbe66f2f34633d9efc0a190
        with:
          github_token: ${{ github.token }}
