name: buf.build
on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  buf:
    name: lint and publish
    runs-on: ubuntu-latest
    if: github.repository_owner == 'prometheus'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1.5.0
        with:
          version: '1.72.0'
          checksum: '8720830e26a733da55bb89bcd3cb44849c0965fc0c44fb5d691cccdc64dca5af'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          setup_only: true
      - name: Lint Protobuf
        run: buf lint prompb --error-format github-actions
      - name: Check Protobuf compatibility
        run: buf breaking prompb --against 'https://github.com/prometheus/prometheus.git#branch=main,ref=HEAD~1,subdir=prompb' --error-format github-actions
        env:
          BUF_INPUT_HTTPS_USERNAME: ${{ github.actor }}
          BUF_INPUT_HTTPS_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Protobuf schema
        run: buf push prompb --label main --label "${GITHUB_SHA}"
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
