name: Build with Werf dev registry

on:
  workflow_run:
    workflows:
      - "Run Tests for C++ Code"
      - "Run Tests for Go Code"
    types: 
      - completed
  push:
    branches:
      - pp
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  WERF_TELEMETRY: "1"
  WERF_TELEMETRY_LOGS: "0"
  WERF_PARALLEL_TASKS_LIMIT: 10

jobs:
  preps:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        ARCH: [arm64, x86_64]
        COMPILATION_MODE: [dbg, opt]
        ASAN: [true, false]
        include:
          - ARCH: arm64
            runner: fsn-dev-arm-runner
          - ARCH: x86_64
            runner: fsn-dev-gitlab-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: deckhouse/modules-actions/setup@v2
        with:
          registry: ${{ secrets.DEV_REGISTRY }}
          registry_login: ${{ secrets.DEV_REGISTRY_LOGIN }}
          registry_password: ${{ secrets.DEV_REGISTRY_PASSWORD }}

      - name: Build Images Dev registry
        run: |
          werf build --add-custom-tag="%image%-${{ github.ref_name }}-${{ env.ARCH }}-${{ matrix.COMPILATION_MODE }}-asan-${{ matrix.ASAN }} --repo=${{ secrets.DEV_REGISTRY }}/prompp/prompp"
