name: Build Test Image

on:
  push:
    branches:
      - pp
    paths:
      - Dockerfile.ci
  pull_request:
    paths:
      - Dockerfile.ci

env:
  BAZEL_VERSION: "7.4.1"
  GO_VERSION: "1.23.2"

jobs:
  build-ci-image:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        ARCH: [arm64, x86_64]
        include:
          - ARCH: arm64
            runner: fsn-dev-arm-runner
            go_arch: arm64
          - ARCH: x86_64
            runner: fsn-dev-gitlab-runner
            go_arch: amd64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_REGISTRY_LOGIN }}
          password: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
          logout: false

      - name: Build and Push Docker Image
        run: |
          docker build -f Dockerfile.ci \
            -t ${{ secrets.CI_REGISTRY_IMAGE }}:gcc-tools-${{ matrix.ARCH }} \
            --build-arg ARCH=${{ matrix.ARCH }} \
            --build-arg BAZEL_ARCH=${{ matrix.ARCH }} \
            --build-arg BAZEL_VERSION=${{ env.BAZEL_VERSION }} \
            --build-arg GO_ARCH=${{ matrix.go_arch }} \
            --build-arg GO_VERSION=${{ env.GO_VERSION }} .
          docker push ${{ secrets.CI_REGISTRY_IMAGE }}:gcc-tools-${{ matrix.ARCH }}
