---
name: CI
on:
  pull_request:
  push:
    branches: [main, 'release-*']
    tags: ['v*']

permissions:
  contents: read

jobs:
  test_go:
    name: Go tests
    runs-on: ubuntu-latest
    container:
      image: quay.io/prometheus/golang-builder:1.26-base
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: go test -v -count=500 -run TestDiskFillingUpAfterDisablingOOO ./tsdb/
      - run: go test -v -count=500 -run TestDiskFillingUpAfterDisablingOOO ./tsdb/
      - run: go test -v -count=500 -run TestDiskFillingUpAfterDisablingOOO ./tsdb/
      - run: go test -v -count=500 -run TestDiskFillingUpAfterDisablingOOO ./tsdb/
