---
name: govulncheck
on:
  pull_request:
    paths:
      - VERSION
      - .github/workflows/govulncheck.yml
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '33 2 * * *'

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@31f7c5463448f83528bd771c2d978d940080c9fd # v1.0.4-unreleased
