name: 'Release note'
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
permissions:
  contents: read

jobs:
  check_release_note:
    name: check
    runs-on: ubuntu-latest
    if: github.repository_owner == 'prometheus' || github.repository_owner == 'prometheus-community' # Don't run this workflow on forks.
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          echo "$PR_DESCRIPTION" | make release-note-check
