---
name: Sync repo files
on:
  schedule:
    - cron: '44 17 * * *'
  workflow_dispatch: {}
permissions:
  contents: read

jobs:
  repo_sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'prometheus'
    container:
      image: quay.io/prometheus/golang-builder
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - run: ./scripts/sync_repo_files.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PROMBOT_REPOSYNC_TOKEN }}
          GITHUB_TOKEN_PROMETHEUS: ${{ secrets.PROMBOT_REPOSYNC_TOKEN_PROMETHEUS }}
          GITHUB_TOKEN_PROMETHEUS_COMMUNITY: ${{ secrets.PROMBOT_REPOSYNC_TOKEN_PROMETHEUS_COMMUNITY }}
